server:
  port: 8080
spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql://localhost:3306/comm-dev
    username: comm
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 2
      max-total: 2
      max-idle: 2
      min-idle: 2
      max-wait-millis: 10000
      validation-query: SELECT 1
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 300000
      num-tests-per-eviction-run: 6
      min-evictable-idle-time-millis: -1
      pool-prepared-statements: true
      max-open-prepared-statements: 50
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
logging:
  config: classpath:logback-dev.xml
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.stat: DEBUG
    org.hibernate.type.BasicTypeRegistry: WARN
